name: flow1
on:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: task1
        run: |
          echo "Task 1 is succesful"
          exit 1
          
      - name: task2
        run: |
          echo "Tasks2 may have issues"
          exit 1
      - name: task3
        id: task3
        run: |
          echo "Task3 will always failed"
          exit 1
      - name: task4
        condition: ne(dependencies.task3.result, 'skipped')
        run: |
          echo "Task4 should always run if error occured or not."
      
        
